version: '3.8'

services:
  database:
    image: postgres:14
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5433:5432'
    volumes:
      - volume_postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.11
    container_name: pgadmin
    ports:
      - 8080:80
    volumes:
      - volume_pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - database

volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga
