version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  node: circleci/node@5.0.2
  serverless-framework: circleci/serverless-framework@2.0.1

jobs:
  build_and_deploy:
    executor: serverless-framework/default
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
      TURBO_TOKEN: $TURBO_TOKEN
      PNPM_HOME: /home/circleci/pnpm
    steps:
      - checkout
      - run:
          name: Update PATH
          command: |
            echo 'export PNPM_HOME=/home/circleci/pnpm' >> $BASH_ENV
            echo 'export PATH=$PNPM_HOME:$PATH' >> $BASH_ENV
            mkdir -p $PNPM_HOME
      - run:
          name: Install pnpm
          command: curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=8.15.1 sh - | node - add --global pnpm
      - run:
          name: Install Dependencies
          command: sudo pnpm install
      - restore_cache:
          keys:
            - pnpm-{{ checksum "pnpm-lock.yaml" }}
      - save_cache:
          key: pnpm-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
      - run:
          name: Install Turborepo
          command: sudo pnpm install -g turbo
      - run:
          name: Build with Turborepo
          command: sudo turbo build
      - aws-cli/setup
      - serverless-framework/setup
      - run:
          command: sudo pnpm --filter api run deploy
          name: deploy

workflows:
  deploy:
    jobs:
      - build_and_deploy
