version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  node: circleci/node@5.0.2
  serverless-framework: circleci/serverless-framework@2.0.1

jobs:
  build_and_deploy:
    executor: serverless-framework/default
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install -g pnpm
      - run:
          name: Install Dependencies
          command: pnpm install
      - run:
          name: Install Turborepo
          command: pnpm install -g turbo
      - run:
          name: Build with Turborepo
          command: turbo build
      - aws-cli/setup
      - serverless-framework/setup
      - run:
          command: pnpm --filter api run deploy
          name: deploy

workflows:
  deploy:
    jobs:
      - build_and_deploy
